import React from "react";
import { createContext, useContext, useEffect, useMemo, useState } from "react";

const en = {
  appName: "Nithin Traveling App",
  home: "Home",
  searchBus: "Search Bus",
  login: "Login",
  register: "Register",
  adminLogin: "Admin Login",
  passenger: "Passenger",
  myBookings: "My Bookings",
  admin: "Admin",
  passengerLogin: "Passenger Login",
  logout: "Logout",
  darkMode: "Dark Mode",
  whiteMode: "White Mode",
  kannada: "Kannada",
  english: "English",
  karnatakaMap: "Karnataka Map",
  karnatakaRoutesOnly: "Karnataka routes only",
  heroTitle: "Book Your Karnataka Bus Journey Easily",
  heroSubtitle: "Safe, simple and fast bus booking across Karnataka",
  bookNow: "Book Now",
  findYourBus: "Find your bus",
  from: "From",
  to: "To",
  journeyDate: "Journey Date",
  "Search Bus": "Search Bus",
  "Login": "Login",
  "Register": "Register",
  "Passenger Login": "Passenger Login",
  "Admin Login": "Admin Login",
  "Toggle menu": "Toggle menu",
  "Ticket style": "Ticket style",
  "Scanned ticket style": "Scanned ticket style",
  "Payment QR code": "Payment QR code",
  "Ticket barcode": "Ticket barcode",
  "From": "From",
  "To": "To",
  "Journey Date": "Journey Date",
  "Karnataka": "Karnataka",
  easyBooking: "Easy Booking",
  easyBookingText: "Search, select, pay and track your ticket from one clean dashboard.",
  karnatakaRoutes: "Karnataka Routes",
  karnatakaRoutesText: "Only verified Karnataka cities and bus stands are available in the app.",
  secureQrPayment: "Secure QR Payment",
  secureQrPaymentText: "Passengers upload transaction details and admins verify each payment.",
  instantTicket: "Instant Ticket",
  instantTicketText: "Download or print your professional ticket after admin confirmation.",
  popularRoutePreview: "Popular route preview",
  premiumCards: "Premium booking cards built for real travel workflows",
  footerDesc: "Safe, simple and fast Karnataka bus booking for students, families and daily travelers.",
  copyright: "Copyright 2026 Nithin Traveling App. All rights reserved.",

  "Dashboard": "Dashboard",
  "Add Bus": "Add Bus",
  "View Bus List": "View Bus List",
  "Upload QR Code": "Upload QR Code",
  "View Bookings": "View Bookings",
  "Payments": "Payments",
  "Passenger Dashboard": "Passenger Dashboard",
  "Search buses, view bookings and manage your profile.": "Search buses, view bookings and manage your profile.",
  "Total Bookings": "Total Bookings",
  "Pending Payments": "Pending Payments",
  "Confirmed Tickets": "Confirmed Tickets",
  "Profile": "Profile",
  "Ready for your next Karnataka journey?": "Ready for your next Karnataka journey?",
  "Search buses by from, to and journey date. Your booking will stay pending until admin confirms payment.":
    "Search buses by from, to and journey date. Your booking will stay pending until admin confirms payment.",
  "Choose only Karnataka bus stands and routes.": "Choose only Karnataka bus stands and routes.",
  "Number of Passengers": "Number of Passengers",
  "Available Buses": "Available Buses",
  "Searching matching Karnataka buses...": "Searching matching Karnataka buses...",
  "No buses found": "No buses found",
  "Try another date or Karnataka route.": "Try another date or Karnataka route.",
  "Search Again": "Search Again",

  "Welcome back, traveler": "Welcome back, traveler",
  "Login to search Karnataka buses, complete QR payments and download confirmed tickets.":
    "Login to search Karnataka buses, complete QR payments and download confirmed tickets.",
  "Email": "Email",
  "Password": "Password",
  "Signing in...": "Signing in...",
  "New passenger?": "New passenger?",
  "Create an account": "Create an account",
  "Passenger Register": "Passenger Register",
  "Full Name": "Full Name",
  "Phone Number": "Phone Number",
  "Confirm Password": "Confirm Password",
  "Creating account...": "Creating account...",
  "Already registered?": "Already registered?",
  "Login here": "Login here",
  "Admin can add buses, upload QR codes and confirm passenger payments.":
    "Admin can add buses, upload QR codes and confirm passenger payments.",
  "Checking access...": "Checking access...",

  "Email and password are required": "Email and password are required",
  "Enter a valid email address": "Enter a valid email address",
  "All fields are required": "All fields are required",
  "Phone number must be 10 digits": "Phone number must be 10 digits",
  "Password must be at least 6 characters": "Password must be at least 6 characters",
  "Passwords do not match": "Passwords do not match",
  "From and To locations cannot be the same": "From and To locations cannot be the same",
  "All search fields are required": "All search fields are required",
  "Something went wrong. Please try again.": "Something went wrong. Please try again.",

  "Booking Details": "Booking Details",
  "Loading bus details": "Loading bus details",
  "Loading booking form...": "Loading booking form...",
  "Passenger Name": "Passenger Name",
  "Age": "Age",
  "Gender": "Gender",
  "Male": "Male",
  "Female": "Female",
  "Other": "Other",
  "Number of Seats": "Number of Seats",
  "Seat Numbers if possible": "Seat Numbers if possible",
  "Example: S1, S2": "Example: S1, S2",
  "Creating booking...": "Creating booking...",
  "Continue to Payment": "Continue to Payment",
  "Fare Summary": "Fare Summary",
  "Ticket Price": "Ticket Price",
  "Seats": "Seats",
  "Total Amount": "Total Amount",
  "Payment status will remain Pending until admin confirms your QR payment.":
    "Payment status will remain Pending until admin confirms your QR payment.",
  "All booking fields are required. Seat numbers are optional.":
    "All booking fields are required. Seat numbers are optional.",
  "Seats requested exceed available seats": "Seats requested exceed available seats",

  "QR Code Payment": "QR Code Payment",
  "Submit the transaction ID after scanning the admin QR code.":
    "Submit the transaction ID after scanning the admin QR code.",
  "Loading payment details...": "Loading payment details...",
  "Route": "Route",
  "Amount": "Amount",
  "Payment": "Payment",
  "Booking": "Booking",
  "Admin QR not uploaded yet": "Admin QR not uploaded yet",
  "Scan this QR code and complete the payment": "Scan this QR code and complete the payment",
  "Transaction ID": "Transaction ID",
  "Upload payment screenshot optional": "Upload payment screenshot optional",
  "Submitting...": "Submitting...",
  "Submit Payment": "Submit Payment",
  "Go back to My Bookings": "Go back to My Bookings",
  "Transaction ID is required before submitting payment": "Transaction ID is required before submitting payment",

  "Track booking status, payment status and confirmed tickets.":
    "Track booking status, payment status and confirmed tickets.",
  "Loading your bookings...": "Loading your bookings...",
  "No bookings yet": "No bookings yet",
  "Ticket": "Ticket",
  "Bus": "Bus",
  "Action": "Action",
  "Pay": "Pay",
  "View confirmed ticket only": "View confirmed ticket only",
  "Pending": "Pending",
  "Confirmed": "Confirmed",
  "Rejected": "Rejected",
  "Cancelled": "Cancelled",
  "Not submitted": "Not submitted",
  "Optional": "Optional",

  "Admin Dashboard": "Admin Dashboard",
  "Manage buses, QR payments and passenger bookings.": "Manage buses, QR payments and passenger bookings.",
  "Total Buses": "Total Buses",
  "Today in control": "Today in control",
  "Upload the payment QR, add Karnataka buses and verify every passenger payment request.":
    "Upload the payment QR, add Karnataka buses and verify every passenger payment request.",
  "confirmed revenue": "confirmed revenue",
  "Upload QR": "Upload QR",
  "Create a new Karnataka route bus schedule.": "Create a new Karnataka route bus schedule.",
  "Edit, delete and monitor available seats.": "Edit, delete and monitor available seats.",
  "Delete this bus from Nithin Traveling App?": "Delete this bus from Nithin Traveling App?",
  "Edit": "Edit",
  "Delete": "Delete",
  "No buses added yet.": "No buses added yet.",
  "Update Bus": "Update Bus",
  "Modify route, driver, fare and seat availability.": "Modify route, driver, fare and seat availability.",
  "Loading bus...": "Loading bus...",

  "Bus Name": "Bus Name",
  "Bus Number": "Bus Number",
  "Bus Type": "Bus Type",
  "From Location": "From Location",
  "To Location": "To Location",
  "Departure Time": "Departure Time",
  "Arrival Time": "Arrival Time",
  "Total Seats": "Total Seats",
  "Available Seats": "Available Seats",
  "Driver Name": "Driver Name",
  "Driver Phone Number": "Driver Phone Number",
  "Bus Image optional": "Bus Image optional",
  "Save Bus": "Save Bus",
  "Saving...": "Saving...",
  "All bus details are required except bus image": "All bus details are required except bus image",
  "Driver phone number must be 10 digits": "Driver phone number must be 10 digits",
  "Available seats cannot exceed total seats": "Available seats cannot exceed total seats",
  "Sleeper": "Sleeper",
  "Semi Sleeper": "Semi Sleeper",
  "AC": "AC",
  "Non-AC": "Non-AC",
  "Express": "Express",

  "Passengers will scan this QR code during payment.": "Passengers will scan this QR code during payment.",
  "QR code image is required": "QR code image is required",
  "QR code uploaded successfully": "QR code uploaded successfully",
  "QR Code Image": "QR Code Image",
  "Uploading...": "Uploading...",
  "Current QR Code": "Current QR Code",
  "Current payment QR": "Current payment QR",
  "No QR code uploaded yet.": "No QR code uploaded yet.",
  "Confirm or reject manual QR payment requests.": "Confirm or reject manual QR payment requests.",
  "Loading all bookings...": "Loading all bookings...",
  "Passenger": "Passenger",
  "Txn ID": "Txn ID",
  "Screenshot": "Screenshot",
  "Status": "Status",
  "View": "View",
  "Confirm": "Confirm",
  "Reject": "Reject",
  "No bookings available yet.": "No bookings available yet.",

  confirmed: "Confirmed",
  premiumTicket: "Premium Karnataka bus journey ticket",
  happyJourney: "Happy Journey",
  shubhaPrayana: "Shubha Prayana",
  kannadaService: "Karnataka Bus Service",
  safeJourneyNote: "Have a safe and happy journey.",
  boardingPass: "Boarding Pass",
  busBoardingPass: "Karnataka bus boarding pass",
  ticketId: "Ticket ID",
  scanViewDownload: "Scan to view details and download",
  scanDetails: "Scan for details",
  route: "Route",
  total: "Total",
  passengerLabel: "Passenger",
  phoneNumber: "Phone Number",
  busLabel: "Bus",
  boardingPlatform: "Boarding Platform",
  timing: "Timing",
  seatNumber: "Seat Number",
  ticketPrice: "Ticket Price",
  payment: "Payment",
  terms: "Terms and Conditions",
  termsText:
    "Carry a valid ID proof. Report at the boarding point 20 minutes before departure. Ticket is valid only for the passenger, route, date and seats printed here. Management is not responsible for delays caused by traffic, weather or government restrictions.",
  date: "Date",
  boarding: "Boarding",
  arrival: "Arrival",
  platform: "Platform",
  seat: "Seat",
  seats: "seat(s)",
  seatsLeft: "seats left",
  busTicket: "Bus Ticket",
  professionalTicket: "Professional Ticket",
  ticketSubtitle: "Download or print your confirmed journey ticket.",
  ticketNotAvailable: "Ticket not available",
  backToDashboard: "Back to Dashboard",
  downloadTicketPdf: "Download Ticket as PDF",
  downloadBoardingPass: "Download Boarding Pass",
  printTicket: "Print Ticket",
  verifiedQrTicket: "Verified QR Ticket",
  ticketDetails: "Nithin Traveling App Ticket Details",
  scannedTicketText: "Scanned ticket details and mobile download options.",
  journey: "Journey",
  downloadTicket: "Download Ticket",
  print: "Print",
  ticket: "Ticket",
  "Auto assigned": "Auto assigned",

  mapHeroTitle: "Karnataka Bus Network Map",
  mapHeroText: "Explore popular Karnataka bus stands, coastal routes, hill stations and northern city connections.",
  mapQuickSearch: "Plan from the map",
  mapNetwork: "Route Network",
  mapNetworkText: "Tap a place idea, then search buses from the dashboard using Karnataka-only locations.",
  mapMajorStands: "Major Bus Stands",
  mapMajorStandsText: "Bengaluru Majestic, Mysuru, Mangaluru, Hubballi and more connected in one booking flow.",
  mapServiceZones: "Service Zones",
  mapServiceZonesText: "Coastal Karnataka, Malnad, North Karnataka and South Karnataka routes are highlighted.",
  openSearch: "Open Search",
  coastalRoute: "Coastal Route",
  malnadRoute: "Malnad Route",
  northKarnataka: "North Karnataka",
  southKarnataka: "South Karnataka",
  routeIdea: "Route idea",
  realKarnatakaMap: "Real Karnataka map",
  liveMap: "Live Karnataka map",
  majorKarnatakaStops: "Major Karnataka stops",
  openInOpenStreetMap: "Open full map in OpenStreetMap",

  "Bengaluru Majestic": "Bengaluru Majestic",
  "Mysuru": "Mysuru",
  "Mangaluru": "Mangaluru",
  "Hubballi": "Hubballi",
  "Dharwad": "Dharwad",
  "Belagavi": "Belagavi",
  "Shivamogga": "Shivamogga",
  "Davangere": "Davangere",
  "Tumakuru": "Tumakuru",
  "Ballari": "Ballari",
  "Hassan": "Hassan",
  "Chikkamagaluru": "Chikkamagaluru",
  "Udupi": "Udupi",
  "Manipal": "Manipal",
  "Karwar": "Karwar",
  "Madikeri": "Madikeri",
  "Mandya": "Mandya",
  "Ramanagara": "Ramanagara",
  "Kolar": "Kolar",
  "Chitradurga": "Chitradurga",
  "Vijayapura": "Vijayapura",
  "Bagalkot": "Bagalkot",
  "Raichur": "Raichur",
  "Kalaburagi": "Kalaburagi",
  "Bidar": "Bidar",
  "Yadgir": "Yadgir",
  "Haveri": "Haveri",
  "Gadag": "Gadag",
  "Chikkaballapur": "Chikkaballapur",
  "Koppal": "Koppal",
  "Hospet": "Hospet",
  "Sirsi": "Sirsi",
  "Sagara": "Sagara",
  "Dandeli": "Dandeli",
  "Gokarna": "Gokarna",
  "Murudeshwar": "Murudeshwar"
};

const kn = {
  appName: "ನಿತಿನ್ ಟ್ರಾವೆಲಿಂಗ್ ಆಪ್",
  home: "ಮುಖಪುಟ",
  searchBus: "ಬಸ್ ಹುಡುಕಿ",
  login: "ಲಾಗಿನ್",
  register: "ನೋಂದಣಿ",
  adminLogin: "ಅಡ್ಮಿನ್ ಲಾಗಿನ್",
  passenger: "ಪ್ರಯಾಣಿಕ",
  myBookings: "ನನ್ನ ಬುಕ್ಕಿಂಗ್‌ಗಳು",
  admin: "ಅಡ್ಮಿನ್",
  passengerLogin: "ಪ್ರಯಾಣಿಕ ಲಾಗಿನ್",
  logout: "ಲಾಗೌಟ್",
  darkMode: "ಡಾರ್ಕ್ ಮೋಡ್",
  whiteMode: "ವೈಟ್ ಮೋಡ್",
  kannada: "ಕನ್ನಡ",
  english: "English",
  karnatakaMap: "ಕರ್ನಾಟಕ ನಕ್ಷೆ",
  karnatakaRoutesOnly: "ಕರ್ನಾಟಕ ಮಾರ್ಗಗಳು ಮಾತ್ರ",
  heroTitle: "ನಿಮ್ಮ ಕರ್ನಾಟಕ ಬಸ್ ಪ್ರಯಾಣವನ್ನು ಸುಲಭವಾಗಿ ಬುಕ್ ಮಾಡಿ",
  heroSubtitle: "ಕರ್ನಾಟಕದಾದ್ಯಂತ ಸುರಕ್ಷಿತ, ಸರಳ ಮತ್ತು ವೇಗದ ಬಸ್ ಬುಕ್ಕಿಂಗ್",
  bookNow: "ಈಗ ಬುಕ್ ಮಾಡಿ",
  findYourBus: "ನಿಮ್ಮ ಬಸ್ ಹುಡುಕಿ",
  from: "ಇಂದ",
  to: "ಗೆ",
  journeyDate: "ಪ್ರಯಾಣ ದಿನಾಂಕ",
  "Search Bus": "ಬಸ್ ಹುಡುಕಿ",
  "Login": "ಲಾಗಿನ್",
  "Register": "ನೋಂದಣಿ",
  "Passenger Login": "ಪ್ರಯಾಣಿಕ ಲಾಗಿನ್",
  "Admin Login": "ಅಡ್ಮಿನ್ ಲಾಗಿನ್",
  "Toggle menu": "ಮೆನು ಬದಲಿಸಿ",
  "Ticket style": "ಟಿಕೆಟ್ ಶೈಲಿ",
  "Scanned ticket style": "ಸ್ಕ್ಯಾನ್ ಟಿಕೆಟ್ ಶೈಲಿ",
  "Payment QR code": "ಪಾವತಿ QR ಕೋಡ್",
  "Ticket barcode": "ಟಿಕೆಟ್ ಬಾರ್‌ಕೋಡ್",
  "From": "ಇಂದ",
  "To": "ಗೆ",
  "Journey Date": "ಪ್ರಯಾಣ ದಿನಾಂಕ",
  "Karnataka": "ಕರ್ನಾಟಕ",
  easyBooking: "ಸುಲಭ ಬುಕ್ಕಿಂಗ್",
  easyBookingText: "ಒಂದೇ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ಹುಡುಕಿ, ಆಯ್ಕೆಮಾಡಿ, ಪಾವತಿಸಿ ಮತ್ತು ಟಿಕೆಟ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
  karnatakaRoutes: "ಕರ್ನಾಟಕ ಮಾರ್ಗಗಳು",
  karnatakaRoutesText: "ಆಪ್‌ನಲ್ಲಿ ಪರಿಶೀಲಿತ ಕರ್ನಾಟಕ ನಗರಗಳು ಮತ್ತು ಬಸ್ ನಿಲ್ದಾಣಗಳು ಮಾತ್ರ ಲಭ್ಯ.",
  secureQrPayment: "ಸುರಕ್ಷಿತ QR ಪಾವತಿ",
  secureQrPaymentText: "ಪ್ರಯಾಣಿಕರು ವ್ಯವಹಾರ ವಿವರಗಳನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡುತ್ತಾರೆ ಮತ್ತು ಅಡ್ಮಿನ್ ಪಾವತಿಯನ್ನು ಪರಿಶೀಲಿಸುತ್ತಾರೆ.",
  instantTicket: "ತಕ್ಷಣದ ಟಿಕೆಟ್",
  instantTicketText: "ಅಡ್ಮಿನ್ ದೃಢೀಕರಣದ ನಂತರ ನಿಮ್ಮ ವೃತ್ತಿಪರ ಟಿಕೆಟ್ ಡೌನ್‌ಲೋಡ್ ಅಥವಾ ಪ್ರಿಂಟ್ ಮಾಡಿ.",
  popularRoutePreview: "ಜನಪ್ರಿಯ ಮಾರ್ಗ ಪೂರ್ವವೀಕ್ಷಣೆ",
  premiumCards: "ನಿಜವಾದ ಪ್ರಯಾಣ ಕಾರ್ಯಗಳಿಗೆ ಪ್ರೀಮಿಯಂ ಬುಕ್ಕಿಂಗ್ ಕಾರ್ಡ್‌ಗಳು",
  footerDesc: "ವಿದ್ಯಾರ್ಥಿಗಳು, ಕುಟುಂಬಗಳು ಮತ್ತು ದೈನಂದಿನ ಪ್ರಯಾಣಿಕರಿಗೆ ಸುರಕ್ಷಿತ ಕರ್ನಾಟಕ ಬಸ್ ಬುಕ್ಕಿಂಗ್.",
  copyright: "ಕಾಪಿರೈಟ್ 2026 ನಿತಿನ್ ಟ್ರಾವೆಲಿಂಗ್ ಆಪ್. ಎಲ್ಲಾ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",

  "Dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
  "Add Bus": "ಬಸ್ ಸೇರಿಸಿ",
  "View Bus List": "ಬಸ್ ಪಟ್ಟಿ ನೋಡಿ",
  "Upload QR Code": "QR ಕೋಡ್ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
  "View Bookings": "ಬುಕ್ಕಿಂಗ್‌ಗಳನ್ನು ನೋಡಿ",
  "Payments": "ಪಾವತಿಗಳು",
  "Passenger Dashboard": "ಪ್ರಯಾಣಿಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
  "Search buses, view bookings and manage your profile.": "ಬಸ್ ಹುಡುಕಿ, ಬುಕ್ಕಿಂಗ್ ನೋಡಿ ಮತ್ತು ಪ್ರೊಫೈಲ್ ನಿರ್ವಹಿಸಿ.",
  "Total Bookings": "ಒಟ್ಟು ಬುಕ್ಕಿಂಗ್‌ಗಳು",
  "Pending Payments": "ಬಾಕಿ ಪಾವತಿಗಳು",
  "Confirmed Tickets": "ದೃಢೀಕೃತ ಟಿಕೆಟ್‌ಗಳು",
  "Profile": "ಪ್ರೊಫೈಲ್",
  "Ready for your next Karnataka journey?": "ಮುಂದಿನ ಕರ್ನಾಟಕ ಪ್ರಯಾಣಕ್ಕೆ ಸಿದ್ಧವೇ?",
  "Search buses by from, to and journey date. Your booking will stay pending until admin confirms payment.":
    "ಇಂದ, ಗೆ ಮತ್ತು ದಿನಾಂಕದ ಆಧಾರದಲ್ಲಿ ಬಸ್ ಹುಡುಕಿ. ಅಡ್ಮಿನ್ ಪಾವತಿ ದೃಢೀಕರಿಸುವವರೆಗೆ ಬುಕ್ಕಿಂಗ್ ಬಾಕಿ ಇರುತ್ತದೆ.",
  "Choose only Karnataka bus stands and routes.": "ಕರ್ನಾಟಕ ಬಸ್ ನಿಲ್ದಾಣಗಳು ಮತ್ತು ಮಾರ್ಗಗಳನ್ನು ಮಾತ್ರ ಆಯ್ಕೆಮಾಡಿ.",
  "Number of Passengers": "ಪ್ರಯಾಣಿಕರ ಸಂಖ್ಯೆ",
  "Available Buses": "ಲಭ್ಯವಿರುವ ಬಸ್‌ಗಳು",
  "Searching matching Karnataka buses...": "ಸರಿಹೊಂದುವ ಕರ್ನಾಟಕ ಬಸ್‌ಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
  "No buses found": "ಬಸ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
  "Try another date or Karnataka route.": "ಇನ್ನೊಂದು ದಿನಾಂಕ ಅಥವಾ ಕರ್ನಾಟಕ ಮಾರ್ಗ ಪ್ರಯತ್ನಿಸಿ.",
  "Search Again": "ಮತ್ತೆ ಹುಡುಕಿ",

  "Welcome back, traveler": "ಮತ್ತೆ ಸ್ವಾಗತ, ಪ್ರಯಾಣಿಕರೇ",
  "Login to search Karnataka buses, complete QR payments and download confirmed tickets.":
    "ಕರ್ನಾಟಕ ಬಸ್‌ಗಳನ್ನು ಹುಡುಕಲು, QR ಪಾವತಿ ಮಾಡಲು ಮತ್ತು ದೃಢೀಕೃತ ಟಿಕೆಟ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ಲಾಗಿನ್ ಮಾಡಿ.",
  "Email": "ಇಮೇಲ್",
  "Password": "ಪಾಸ್‌ವರ್ಡ್",
  "Signing in...": "ಲಾಗಿನ್ ಆಗುತ್ತಿದೆ...",
  "New passenger?": "ಹೊಸ ಪ್ರಯಾಣಿಕರಾ?",
  "Create an account": "ಖಾತೆ ರಚಿಸಿ",
  "Passenger Register": "ಪ್ರಯಾಣಿಕ ನೋಂದಣಿ",
  "Full Name": "ಪೂರ್ಣ ಹೆಸರು",
  "Phone Number": "ಫೋನ್ ಸಂಖ್ಯೆ",
  "Confirm Password": "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
  "Creating account...": "ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ...",
  "Already registered?": "ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಿದ್ದೀರಾ?",
  "Login here": "ಇಲ್ಲಿ ಲಾಗಿನ್ ಮಾಡಿ",
  "Admin can add buses, upload QR codes and confirm passenger payments.":
    "ಅಡ್ಮಿನ್ ಬಸ್ ಸೇರಿಸಬಹುದು, QR ಕೋಡ್ ಅಪ್ಲೋಡ್ ಮಾಡಬಹುದು ಮತ್ತು ಪ್ರಯಾಣಿಕರ ಪಾವತಿಗಳನ್ನು ದೃಢೀಕರಿಸಬಹುದು.",
  "Checking access...": "ಪ್ರವೇಶ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",

  "Email and password are required": "ಇಮೇಲ್ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ ಅಗತ್ಯ",
  "Enter a valid email address": "ಸರಿಯಾದ ಇಮೇಲ್ ವಿಳಾಸ ನಮೂದಿಸಿ",
  "All fields are required": "ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳು ಅಗತ್ಯ",
  "Phone number must be 10 digits": "ಫೋನ್ ಸಂಖ್ಯೆ 10 ಅಂಕಿಗಳಿರಬೇಕು",
  "Password must be at least 6 characters": "ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳಿರಬೇಕು",
  "Passwords do not match": "ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ",
  "From and To locations cannot be the same": "ಇಂದ ಮತ್ತು ಗೆ ಸ್ಥಳಗಳು ಒಂದೇ ಆಗಿರಬಾರದು",
  "All search fields are required": "ಎಲ್ಲಾ ಹುಡುಕಾಟ ಕ್ಷೇತ್ರಗಳು ಅಗತ್ಯ",
  "Something went wrong. Please try again.": "ಏನೋ ತಪ್ಪಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",

  "Booking Details": "ಬುಕ್ಕಿಂಗ್ ವಿವರಗಳು",
  "Loading bus details": "ಬಸ್ ವಿವರಗಳು ಲೋಡ್ ಆಗುತ್ತಿದೆ",
  "Loading booking form...": "ಬುಕ್ಕಿಂಗ್ ಫಾರ್ಮ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
  "Passenger Name": "ಪ್ರಯಾಣಿಕರ ಹೆಸರು",
  "Age": "ವಯಸ್ಸು",
  "Gender": "ಲಿಂಗ",
  "Male": "ಪುರುಷ",
  "Female": "ಮಹಿಳೆ",
  "Other": "ಇತರೆ",
  "Number of Seats": "ಸೀಟ್‌ಗಳ ಸಂಖ್ಯೆ",
  "Seat Numbers if possible": "ಸಾಧ್ಯವಾದರೆ ಸೀಟ್ ಸಂಖ್ಯೆಗಳು",
  "Example: S1, S2": "ಉದಾಹರಣೆ: S1, S2",
  "Creating booking...": "ಬುಕ್ಕಿಂಗ್ ರಚಿಸಲಾಗುತ್ತಿದೆ...",
  "Continue to Payment": "ಪಾವತಿಗೆ ಮುಂದುವರಿಸಿ",
  "Fare Summary": "ಭಾಡಿ ಸಾರಾಂಶ",
  "Ticket Price": "ಟಿಕೆಟ್ ದರ",
  "Seats": "ಸೀಟ್‌ಗಳು",
  "Total Amount": "ಒಟ್ಟು ಮೊತ್ತ",
  "Payment status will remain Pending until admin confirms your QR payment.":
    "ಅಡ್ಮಿನ್ ನಿಮ್ಮ QR ಪಾವತಿಯನ್ನು ದೃಢೀಕರಿಸುವವರೆಗೆ ಪಾವತಿ ಸ್ಥಿತಿ ಬಾಕಿ ಇರುತ್ತದೆ.",
  "All booking fields are required. Seat numbers are optional.": "ಎಲ್ಲಾ ಬುಕ್ಕಿಂಗ್ ಕ್ಷೇತ್ರಗಳು ಅಗತ್ಯ. ಸೀಟ್ ಸಂಖ್ಯೆಗಳು ಐಚ್ಛಿಕ.",
  "Seats requested exceed available seats": "ಕೋರಿದ ಸೀಟ್‌ಗಳು ಲಭ್ಯವಿರುವ ಸೀಟ್‌ಗಳನ್ನು ಮೀರಿವೆ",

  "QR Code Payment": "QR ಕೋಡ್ ಪಾವತಿ",
  "Submit the transaction ID after scanning the admin QR code.": "ಅಡ್ಮಿನ್ QR ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿದ ನಂತರ ವ್ಯವಹಾರ ID ಸಲ್ಲಿಸಿ.",
  "Loading payment details...": "ಪಾವತಿ ವಿವರಗಳು ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
  "Route": "ಮಾರ್ಗ",
  "Amount": "ಮೊತ್ತ",
  "Payment": "ಪಾವತಿ",
  "Booking": "ಬುಕ್ಕಿಂಗ್",
  "Admin QR not uploaded yet": "ಅಡ್ಮಿನ್ QR ಇನ್ನೂ ಅಪ್ಲೋಡ್ ಮಾಡಿಲ್ಲ",
  "Scan this QR code and complete the payment": "ಈ QR ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಪಾವತಿ ಪೂರ್ಣಗೊಳಿಸಿ",
  "Transaction ID": "ವ್ಯವಹಾರ ID",
  "Upload payment screenshot optional": "ಪಾವತಿ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅಪ್ಲೋಡ್ ಐಚ್ಛಿಕ",
  "Submitting...": "ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...",
  "Submit Payment": "ಪಾವತಿ ಸಲ್ಲಿಸಿ",
  "Go back to My Bookings": "ನನ್ನ ಬುಕ್ಕಿಂಗ್‌ಗಳಿಗೆ ಹಿಂದಿರುಗಿ",
  "Transaction ID is required before submitting payment": "ಪಾವತಿ ಸಲ್ಲಿಸುವ ಮೊದಲು ವ್ಯವಹಾರ ID ಅಗತ್ಯ",

  "Track booking status, payment status and confirmed tickets.": "ಬುಕ್ಕಿಂಗ್ ಸ್ಥಿತಿ, ಪಾವತಿ ಸ್ಥಿತಿ ಮತ್ತು ದೃಢೀಕೃತ ಟಿಕೆಟ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
  "Loading your bookings...": "ನಿಮ್ಮ ಬುಕ್ಕಿಂಗ್‌ಗಳು ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
  "No bookings yet": "ಇನ್ನೂ ಬುಕ್ಕಿಂಗ್ ಇಲ್ಲ",
  "Ticket": "ಟಿಕೆಟ್",
  "Bus": "ಬಸ್",
  "Action": "ಕ್ರಿಯೆ",
  "Pay": "ಪಾವತಿಸಿ",
  "View confirmed ticket only": "ದೃಢೀಕೃತ ಟಿಕೆಟ್ ಮಾತ್ರ ನೋಡಿ",
  "Pending": "ಬಾಕಿ",
  "Confirmed": "ದೃಢೀಕೃತ",
  "Rejected": "ನಿರಾಕರಿಸಲಾಗಿದೆ",
  "Cancelled": "ರದ್ದು",
  "Not submitted": "ಸಲ್ಲಿಸಿಲ್ಲ",
  "Optional": "ಐಚ್ಛಿಕ",

  "Admin Dashboard": "ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
  "Manage buses, QR payments and passenger bookings.": "ಬಸ್‌ಗಳು, QR ಪಾವತಿಗಳು ಮತ್ತು ಪ್ರಯಾಣಿಕರ ಬುಕ್ಕಿಂಗ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
  "Total Buses": "ಒಟ್ಟು ಬಸ್‌ಗಳು",
  "Today in control": "ಇಂದಿನ ನಿಯಂತ್ರಣ",
  "Upload the payment QR, add Karnataka buses and verify every passenger payment request.":
    "ಪಾವತಿ QR ಅಪ್ಲೋಡ್ ಮಾಡಿ, ಕರ್ನಾಟಕ ಬಸ್ ಸೇರಿಸಿ ಮತ್ತು ಪ್ರತಿಯೊಂದು ಪ್ರಯಾಣಿಕರ ಪಾವತಿ ವಿನಂತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ.",
  "confirmed revenue": "ದೃಢೀಕೃತ ಆದಾಯ",
  "Upload QR": "QR ಅಪ್ಲೋಡ್",
  "Create a new Karnataka route bus schedule.": "ಹೊಸ ಕರ್ನಾಟಕ ಮಾರ್ಗ ಬಸ್ ವೇಳಾಪಟ್ಟಿ ರಚಿಸಿ.",
  "Edit, delete and monitor available seats.": "ಲಭ್ಯವಿರುವ ಸೀಟ್‌ಗಳನ್ನು ಸಂಪಾದಿಸಿ, ಅಳಿಸಿ ಮತ್ತು ಗಮನಿಸಿ.",
  "Delete this bus from Nithin Traveling App?": "ಈ ಬಸ್ ಅನ್ನು ನಿತಿನ್ ಟ್ರಾವೆಲಿಂಗ್ ಆಪ್‌ನಿಂದ ಅಳಿಸಬೇಕೇ?",
  "Edit": "ಸಂಪಾದಿಸಿ",
  "Delete": "ಅಳಿಸಿ",
  "No buses added yet.": "ಇನ್ನೂ ಬಸ್ ಸೇರಿಸಿಲ್ಲ.",
  "Update Bus": "ಬಸ್ ನವೀಕರಿಸಿ",
  "Modify route, driver, fare and seat availability.": "ಮಾರ್ಗ, ಚಾಲಕ, ಭಾಡಿ ಮತ್ತು ಸೀಟ್ ಲಭ್ಯತೆ ಬದಲಾಯಿಸಿ.",
  "Loading bus...": "ಬಸ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",

  "Bus Name": "ಬಸ್ ಹೆಸರು",
  "Bus Number": "ಬಸ್ ಸಂಖ್ಯೆ",
  "Bus Type": "ಬಸ್ ಪ್ರಕಾರ",
  "From Location": "ಇಂದ ಸ್ಥಳ",
  "To Location": "ಗೆ ಸ್ಥಳ",
  "Departure Time": "ಹೊರಡುವ ಸಮಯ",
  "Arrival Time": "ಬರುವ ಸಮಯ",
  "Total Seats": "ಒಟ್ಟು ಸೀಟ್‌ಗಳು",
  "Available Seats": "ಲಭ್ಯವಿರುವ ಸೀಟ್‌ಗಳು",
  "Driver Name": "ಚಾಲಕರ ಹೆಸರು",
  "Driver Phone Number": "ಚಾಲಕರ ಫೋನ್ ಸಂಖ್ಯೆ",
  "Bus Image optional": "ಬಸ್ ಚಿತ್ರ ಐಚ್ಛಿಕ",
  "Save Bus": "ಬಸ್ ಉಳಿಸಿ",
  "Saving...": "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
  "All bus details are required except bus image": "ಬಸ್ ಚಿತ್ರ ಹೊರತುಪಡಿಸಿ ಎಲ್ಲಾ ಬಸ್ ವಿವರಗಳು ಅಗತ್ಯ",
  "Driver phone number must be 10 digits": "ಚಾಲಕರ ಫೋನ್ ಸಂಖ್ಯೆ 10 ಅಂಕಿಗಳಿರಬೇಕು",
  "Available seats cannot exceed total seats": "ಲಭ್ಯ ಸೀಟ್‌ಗಳು ಒಟ್ಟು ಸೀಟ್‌ಗಳನ್ನು ಮೀರಬಾರದು",
  "Sleeper": "ಸ್ಲೀಪರ್",
  "Semi Sleeper": "ಸೆಮಿ ಸ್ಲೀಪರ್",
  "AC": "ಎಸಿ",
  "Non-AC": "ನಾನ್-ಎಸಿ",
  "Express": "ಎಕ್ಸ್‌ಪ್ರೆಸ್",

  "Passengers will scan this QR code during payment.": "ಪಾವತಿಯ ವೇಳೆ ಪ್ರಯಾಣಿಕರು ಈ QR ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡುತ್ತಾರೆ.",
  "QR code image is required": "QR ಕೋಡ್ ಚಿತ್ರ ಅಗತ್ಯ",
  "QR code uploaded successfully": "QR ಕೋಡ್ ಯಶಸ್ವಿಯಾಗಿ ಅಪ್ಲೋಡ್ ಆಯಿತು",
  "QR Code Image": "QR ಕೋಡ್ ಚಿತ್ರ",
  "Uploading...": "ಅಪ್ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
  "Current QR Code": "ಪ್ರಸ್ತುತ QR ಕೋಡ್",
  "Current payment QR": "ಪ್ರಸ್ತುತ ಪಾವತಿ QR",
  "No QR code uploaded yet.": "ಇನ್ನೂ QR ಕೋಡ್ ಅಪ್ಲೋಡ್ ಮಾಡಿಲ್ಲ.",
  "Confirm or reject manual QR payment requests.": "ಮ್ಯಾನುಯಲ್ QR ಪಾವತಿ ವಿನಂತಿಗಳನ್ನು ದೃಢೀಕರಿಸಿ ಅಥವಾ ನಿರಾಕರಿಸಿ.",
  "Loading all bookings...": "ಎಲ್ಲಾ ಬುಕ್ಕಿಂಗ್‌ಗಳು ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
  "Passenger": "ಪ್ರಯಾಣಿಕ",
  "Txn ID": "Txn ID",
  "Screenshot": "ಸ್ಕ್ರೀನ್‌ಶಾಟ್",
  "Status": "ಸ್ಥಿತಿ",
  "View": "ನೋಡಿ",
  "Confirm": "ದೃಢೀಕರಿಸಿ",
  "Reject": "ನಿರಾಕರಿಸಿ",
  "No bookings available yet.": "ಇನ್ನೂ ಬುಕ್ಕಿಂಗ್‌ಗಳು ಲಭ್ಯವಿಲ್ಲ.",

  confirmed: "ದೃಢೀಕೃತ",
  premiumTicket: "ಪ್ರೀಮಿಯಂ ಕರ್ನಾಟಕ ಬಸ್ ಪ್ರಯಾಣ ಟಿಕೆಟ್",
  happyJourney: "ಸುಖಕರ ಪ್ರಯಾಣ",
  shubhaPrayana: "ಶುಭ ಪ್ರಯಾಣ",
  kannadaService: "ಕರ್ನಾಟಕ ಬಸ್ ಸೇವೆ",
  safeJourneyNote: "ನಿಮ್ಮ ಪ್ರಯಾಣ ಸುಖಕರವಾಗಿರಲಿ.",
  boardingPass: "ಬೋರ್ಡಿಂಗ್ ಪಾಸ್",
  busBoardingPass: "ಕರ್ನಾಟಕ ಬಸ್ ಬೋರ್ಡಿಂಗ್ ಪಾಸ್",
  ticketId: "ಟಿಕೆಟ್ ID",
  scanViewDownload: "ವಿವರ ನೋಡಲು ಮತ್ತು ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
  scanDetails: "ವಿವರಗಳಿಗೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
  route: "ಮಾರ್ಗ",
  total: "ಒಟ್ಟು",
  passengerLabel: "ಪ್ರಯಾಣಿಕ",
  phoneNumber: "ಫೋನ್ ಸಂಖ್ಯೆ",
  busLabel: "ಬಸ್",
  boardingPlatform: "ಬೋರ್ಡಿಂಗ್ ವೇದಿಕೆ",
  timing: "ಸಮಯ",
  seatNumber: "ಸೀಟ್ ಸಂಖ್ಯೆ",
  ticketPrice: "ಟಿಕೆಟ್ ದರ",
  payment: "ಪಾವತಿ",
  terms: "ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು",
  termsText:
    "ಮಾನ್ಯ ಗುರುತಿನ ಚೀಟಿ ಕೊಂಡೊಯ್ಯಿರಿ. ಹೊರಡುವುದಕ್ಕೆ 20 ನಿಮಿಷ ಮೊದಲು ಬೋರ್ಡಿಂಗ್ ಸ್ಥಳಕ್ಕೆ ಬನ್ನಿ. ಈ ಟಿಕೆಟ್ ಮುದ್ರಿತ ಪ್ರಯಾಣಿಕ, ಮಾರ್ಗ, ದಿನಾಂಕ ಮತ್ತು ಸೀಟ್‌ಗಳಿಗೆ ಮಾತ್ರ ಮಾನ್ಯ.",
  date: "ದಿನಾಂಕ",
  boarding: "ಬೋರ್ಡಿಂಗ್",
  arrival: "ಆಗಮನ",
  platform: "ವೇದಿಕೆ",
  seat: "ಸೀಟ್",
  seats: "ಸೀಟ್",
  seatsLeft: "ಸೀಟ್‌ಗಳು ಉಳಿದಿವೆ",
  busTicket: "ಬಸ್ ಟಿಕೆಟ್",
  professionalTicket: "ವೃತ್ತಿಪರ ಟಿಕೆಟ್",
  ticketSubtitle: "ನಿಮ್ಮ ದೃಢೀಕೃತ ಪ್ರಯಾಣ ಟಿಕೆಟ್ ಡೌನ್‌ಲೋಡ್ ಅಥವಾ ಪ್ರಿಂಟ್ ಮಾಡಿ.",
  ticketNotAvailable: "ಟಿಕೆಟ್ ಲಭ್ಯವಿಲ್ಲ",
  backToDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂದಿರುಗಿ",
  downloadTicketPdf: "ಟಿಕೆಟ್ PDF ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
  downloadBoardingPass: "ಬೋರ್ಡಿಂಗ್ ಪಾಸ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
  printTicket: "ಟಿಕೆಟ್ ಪ್ರಿಂಟ್ ಮಾಡಿ",
  verifiedQrTicket: "ದೃಢೀಕೃತ QR ಟಿಕೆಟ್",
  ticketDetails: "ನಿತಿನ್ ಟ್ರಾವೆಲಿಂಗ್ ಆಪ್ ಟಿಕೆಟ್ ವಿವರಗಳು",
  scannedTicketText: "ಸ್ಕ್ಯಾನ್ ಮಾಡಿದ ಟಿಕೆಟ್ ವಿವರಗಳು ಮತ್ತು ಮೊಬೈಲ್ ಡೌನ್‌ಲೋಡ್ ಆಯ್ಕೆಗಳು.",
  journey: "ಪ್ರಯಾಣ",
  downloadTicket: "ಟಿಕೆಟ್ ಡೌನ್‌ಲೋಡ್",
  print: "ಪ್ರಿಂಟ್",
  ticket: "ಟಿಕೆಟ್",
  "Auto assigned": "ಸ್ವಯಂ ನೀಡಲಾಗಿದೆ",

  mapHeroTitle: "ಕರ್ನಾಟಕ ಬಸ್ ನೆಟ್‌ವರ್ಕ್ ನಕ್ಷೆ",
  mapHeroText: "ಜನಪ್ರಿಯ ಕರ್ನಾಟಕ ಬಸ್ ನಿಲ್ದಾಣಗಳು, ಕರಾವಳಿ ಮಾರ್ಗಗಳು, ಮಲೆನಾಡು ಮತ್ತು ಉತ್ತರ ಕರ್ನಾಟಕ ಸಂಪರ್ಕಗಳನ್ನು ನೋಡಿ.",
  mapQuickSearch: "ನಕ್ಷೆಯಿಂದ ಯೋಜಿಸಿ",
  mapNetwork: "ಮಾರ್ಗ ನೆಟ್‌ವರ್ಕ್",
  mapNetworkText: "ಸ್ಥಳದ ಕಲ್ಪನೆ ನೋಡಿ, ನಂತರ ಕರ್ನಾಟಕ ಸ್ಥಳಗಳೊಂದಿಗೆ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ಬಸ್ ಹುಡುಕಿ.",
  mapMajorStands: "ಮುಖ್ಯ ಬಸ್ ನಿಲ್ದಾಣಗಳು",
  mapMajorStandsText: "ಬೆಂಗಳೂರು ಮೆಜೆಸ್ಟಿಕ್, ಮೈಸೂರು, ಮಂಗಳೂರು, ಹುಬ್ಬಳ್ಳಿ ಮತ್ತು ಇನ್ನಷ್ಟು ಒಂದೇ ಬುಕ್ಕಿಂಗ್ ಪ್ರವಾಹದಲ್ಲಿ.",
  mapServiceZones: "ಸೇವಾ ವಲಯಗಳು",
  mapServiceZonesText: "ಕರಾವಳಿ ಕರ್ನಾಟಕ, ಮಲೆನಾಡು, ಉತ್ತರ ಕರ್ನಾಟಕ ಮತ್ತು ದಕ್ಷಿಣ ಕರ್ನಾಟಕ ಮಾರ್ಗಗಳನ್ನು ಹೈಲೈಟ್ ಮಾಡಲಾಗಿದೆ.",
  openSearch: "ಹುಡುಕಾಟ ತೆರೆಯಿರಿ",
  coastalRoute: "ಕರಾವಳಿ ಮಾರ್ಗ",
  malnadRoute: "ಮಲೆನಾಡು ಮಾರ್ಗ",
  northKarnataka: "ಉತ್ತರ ಕರ್ನಾಟಕ",
  southKarnataka: "ದಕ್ಷಿಣ ಕರ್ನಾಟಕ",
  routeIdea: "ಮಾರ್ಗ ಕಲ್ಪನೆ",
  realKarnatakaMap: "ನೈಜ ಕರ್ನಾಟಕ ನಕ್ಷೆ",
  liveMap: "ಲೈವ್ ಕರ್ನಾಟಕ ನಕ್ಷೆ",
  majorKarnatakaStops: "ಮುಖ್ಯ ಕರ್ನಾಟಕ ನಿಲ್ದಾಣಗಳು",
  openInOpenStreetMap: "OpenStreetMap ನಲ್ಲಿ ಪೂರ್ಣ ನಕ್ಷೆ ತೆರೆಯಿರಿ",

  "Bengaluru Majestic": "ಬೆಂಗಳೂರು ಮೆಜೆಸ್ಟಿಕ್",
  "Mysuru": "ಮೈಸೂರು",
  "Mangaluru": "ಮಂಗಳೂರು",
  "Hubballi": "ಹುಬ್ಬಳ್ಳಿ",
  "Dharwad": "ಧಾರವಾಡ",
  "Belagavi": "ಬೆಳಗಾವಿ",
  "Shivamogga": "ಶಿವಮೊಗ್ಗ",
  "Davangere": "ದಾವಣಗೆರೆ",
  "Tumakuru": "ತುಮಕೂರು",
  "Ballari": "ಬಳ್ಳಾರಿ",
  "Hassan": "ಹಾಸನ",
  "Chikkamagaluru": "ಚಿಕ್ಕಮಗಳೂರು",
  "Udupi": "ಉಡುಪಿ",
  "Manipal": "ಮಣಿಪಾಲ್",
  "Karwar": "ಕಾರವಾರ",
  "Madikeri": "ಮಡಿಕೇರಿ",
  "Mandya": "ಮಂಡ್ಯ",
  "Ramanagara": "ರಾಮನಗರ",
  "Kolar": "ಕೋಲಾರ",
  "Chitradurga": "ಚಿತ್ರದುರ್ಗ",
  "Vijayapura": "ವಿಜಯಪುರ",
  "Bagalkot": "ಬಾಗಲಕೋಟೆ",
  "Raichur": "ರಾಯಚೂರು",
  "Kalaburagi": "ಕಲಬುರಗಿ",
  "Bidar": "ಬೀದರ್",
  "Yadgir": "ಯಾದಗಿರಿ",
  "Haveri": "ಹಾವೇರಿ",
  "Gadag": "ಗದಗ",
  "Chikkaballapur": "ಚಿಕ್ಕಬಳ್ಳಾಪುರ",
  "Koppal": "ಕೊಪ್ಪಳ",
  "Hospet": "ಹೊಸಪೇಟೆ",
  "Sirsi": "ಶಿರಸಿ",
  "Sagara": "ಸಾಗರ",
  "Dandeli": "ದಾಂಡೇಲಿ",
  "Gokarna": "ಗೋಕರ್ಣ",
  "Murudeshwar": "ಮುರುಡೇಶ್ವರ"
};

const translations = { en, kn };

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem("nta_language") || "en");

  useEffect(() => {
    localStorage.setItem("nta_language", language);
    document.documentElement.lang = language === "kn" ? "kn" : "en";
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      toggleLanguage: () => setLanguage((value) => (value === "en" ? "kn" : "en")),
      t: (key) => {
        if (key === null || key === undefined) {
          return "";
        }
        const text = String(key);
        return translations[language]?.[text] || translations.en[text] || text;
      }
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
